version: '3.8'

services:
  tech-interview-agency:
    build:
      context: .         # Use the current directory as the build context
      dockerfile: Dockerfile  # Specify the Dockerfile (default is "Dockerfile")
    ports:
      - "7860:7860"      # Map container port 7860 to host port 7860
    volumes:
      - .:/app  # Sync local directory to container's working directory (optional)
    environment:
      - OPENAI_API_KEY=your-api-key  # Set any environment variables needed
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    command: python TechInterviewAgency/agency.py  # Specify the command to run the app
networks:
  tech_interview_network:
    driver: bridge